name: StandardRB

on:
  pull_request:
  push:

jobs:
  standard:
    name: StandardRB Check Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Run standardrb
        run: bundle exec standardrb --format progress
